### PR TITLE
cgame: Add some popumessages defaults

### PR DESCRIPTION
**Pull request by Vorschreibung**

### CODE REVIEW

**Comment by mittermichal** [comment]
why filtering out pickups and team joins by default?

**Comment by Aciz** [comment]
I really don't agree with doing any of these by default.

**Comment by Vorschreibung** [comment]
The nays have it.

**Comment by mittermichal** [comment]
we still love you

**Comment by Vorschreibung** [comment]
I appreciate that, but you could send a bit of that love as well to players who have to suffer the current default config who have excessively long text messages fill their screen literally up to where their crosshair is :')

In case people have forgotten how the game actually looks like by default:
image

**Comment by mittermichal** [comment]
popupmessage component width could be lowered instead

**Comment by Vorschreibung** [comment]
> popupmessage component width could be lowered instead

7 messages is already ridiculously low when simply standing in front of an ammo dispenser will fill them up via `Picked up ammo` messages within mere seconds

reducing the width would just cause linebreaks

please don't take this the wrong way, but I've already tried quite a number of things - there are no trivial solutions to this and the status quo is pretty much completely nonsense and the default experience suffers greatly under it

**Pull request closed without merging**
