### PR TITLE
misc: update 64 bit section in README.md

### PR DESCRIPTION
**Pull request by suburbski**

### CODE REVIEW

**Comment by rmarquis** [comment]
Might be a good opportunity to add the [relevant link](https://github.com/etlegacy/etlegacy/wiki/Compatible-Mods) too.

**Comment by rmarquis** [comment]
Thx!

**Comment by suburbski** [comment]
Note that the Linux section under notes in that link is outdated as well, you can probably get rid of it as the overview says pretty much everything for Linux

**Comment by kuromiii** [comment]
Latest versions of N!tmod (2.3.4) are also compatible with 64 bit, both for Mac and Linux

**Pull request merged**
