### PR TITLE
mod: fix FT icon displaying upside down on 2.60b clients, refs #1794

### PR DESCRIPTION
**Pull request by Aciz**
The TGA had wrong field orientation (top-left), fixed by making it bottom-left.

### CODE REVIEW

**Comment by rmarquis** [comment]
Thanks! Mystery solved.

**Comment by rmarquis** [comment]
Do you mind quickly explaining where I could check this orientation info? Couldn't find anything (simply using paint.net here). So I don't introduce the same issue in new icons.

**Comment by Aciz** [comment]
I personally use [XnView](https://www.xnview.com/en/xnview/) as a general image browser, and I can check it there by right clicking and checking properties. I have no clue about paint.net, but when saving a TGA image, if there is some sort of option dialog, you should check there if it allows you to set the field order. Photoshop does the correct thing by default, but for example Krita does it the wrong way, with no way to change it.

image

While saving image with XnView, bottom up needs to be checked:

image

**Comment by Aciz** [comment]
Quickly looked at paint.net, doesn't seem like there is anything to change the order but it does Bottom-Left by default.

image

**Comment by rmarquis** [comment]
Thank you for the detailed answer! I checked the new obj status icons with XnView, and there're correctly oriented.

I guess the FT issue was introduced because it's not possible to draw a triangle upside down by default in paint.net, so I draw it with the spike on top before flipping it.

**Pull request merged**
