### PR TITLE
Install mod description.txt as non-executable

### PR DESCRIPTION
**Pull request by pemensik**
There is nothing to execute inside it, make sure it stays just readable.

### CODE REVIEW

**Comment by ensiform** [comment]
It's pointless. All mods ship with this file anyway and the game never does anything but read it.

**Comment by pemensik** [comment]
It is not pointless. It had to be fixed by my [rpmfusion package](https://bugzilla.rpmfusion.org/show_bug.cgi?id=5824), because automated tools scan all installed executable files. Executable file without #!/bin/sh fails whole build.

It is small change, but that file should not be executable. It is made executable during install for no reason. It is correctly without executable bit in source repository and should stay it after install.

**Comment by ensiform** [comment]
Understood. Didn't realize it was a mistake on that part.

**Comment by rmarquis** [comment]
Thanks, merged!

**Pull request merged**
