### PR TITLE
game: Default sv_fps to 40

### PR DESCRIPTION
**Pull request by Vorschreibung**
See https://github.com/etlegacy/etlegacy/issues/2555

### CODE REVIEW

**Comment by mittermichal** [comment]
I think there are more places in repo where sv_fps is set to 20

**Comment by Aciz** [comment]
> I think there are more places in repo where sv_fps is set to 20

You want to do it this way so that only legacy mod sets it to 40 by default. If you change the cvar default value in engine, you will break all other mods out of box which have no `sv_fps` fixes.

Edit: if this is adjusted, then @Vorschreibung you'd likely want to set `snaps 40` by default too in cgame.

**Comment by Vorschreibung** [comment]
As the upcoming Release will be the first Release with the Flamethrower `sv_fps` fix - I guess it makes sense to wait another Release and to see that everything continues to work on 20+ `sv_fps` as intended before making it default.

**Comment by x0rnn** [comment]
Shouldn't the server configs also get changed? Different mods use different server configs in their respective mod folder.

Also, g_maxWarp should be changed to 8 with sv_fps 40.

**Pull request closed without merging**
