### PR TITLE
mod: SVG weapon icons

### PR DESCRIPTION
**Pull request by WuTangH**
Adding new weapon icons in .SVG format, which can be seen in fireteams, shoutcaster mode or obituaries.
Icons have black strokes, but testing on bright/snowy maps would be good.

Can be also used for simple item icons maybe?

refs #1433 
refs #218

### CODE REVIEW

**Comment by isRyven** [comment]
Why would you remove old weapon icons? They could serve as a fallback for vet clients.

**Comment by WuTangH** [comment]
True, didnt think about vet players on legacy servers... VET throws warnings and uses large icons instead, which doesnt look good. 
Keeping both seems to work alright on both clients.

**Comment by jackeri** [comment]
Screenshot comparisons would be really nice for tickets like these :)

**Comment by WuTangH** [comment]
Ah right, added some pictures to the 1st post.

**Pull request merged**
