### PR TITLE
etmain: Fix climbing animations

### PR DESCRIPTION
**Pull request by Vorschreibung**
Climbing animations went through a regression between OG 2.60b ET and
current ETL, this commit addresses these regressions and cleans climbing
animations up along it.

- 'climb_dis' and 'climb_start' were way too slow and lengthy - causing
  the bugged-looking animations when leaving or entering a ladder

- 'climb_start' was effectly ditched, as it's rarely played and causes
  the player model to clip into the terrain on most occassions

- note that 'climb_dis' is actually played always when leaving a ladder,
  this means it's played both when climbing up and leaving the ladder,
  but also just the same when climbing down and leaving the ladder

- sometimes when grabbing a ladder to climb up, a jump animation is
  played, this is due to a kickoff/OTG event which plays the jump
  animation and is dependent on the surface one stands on when grabbing
  the ladder - this is addressed by gating the animation behind an
  additional check for being on a ladder

- when grabbing al adder to climb down, a jump animation is also played
  via 'PM_GroundTraceMissed'/freefall, as when falling onto a ladder
  from above, for a few frames there is no contact yet with the ladder -
  to remedy this, the 'ANIM_ET_CLIMB_MOUNT' animation, which triggers
  shortly after is set to 'force' to overrule the few animation frames
  of the previous jump animation

- 'climb_up' was way too fast, climbing looked comical, made slower

- 'climb_down' was too fast, made slower

### CODE REVIEW

**Comment by Vorschreibung** [comment]
OG ET 2.60b: https://www.youtube.com/watch?v=qhLELEreCMU
pre-commit: https://www.youtube.com/watch?v=2h5D83LXG_g
post-commit: https://www.youtube.com/watch?v=UTAz_GEgqNo

**Comment by Vorschreibung** [comment]
A bunch of comments on this:

1. `climb_dis` and `climb_start` were **way** too slow and lengthy - causing the bugged-looking animations when leaving or entering a ladder
2. sometimes when entering/grabbing a ladder, a jump animation is played, this is seemingly due to a kickoff/OTG event which plays the jump animation and dependent on the surface one stands on when grabbing the ladder - and which is not addressed in this commit, but can be addressed separately if need be
3. `climb_up` was too fast on ETL in comparison to 2.60b, made slower
4. `climb_down` was too fast on ETL in comparison to 2.60b, made slower

**Comment by Vorschreibung** [comment]
**IMPORTANT** Should only be merged _AFTER_ merging: https://github.com/etlegacy/etlegacy/pull/2620

**Comment by Aranud** [comment]
Potential fix for https://github.com/etlegacy/etlegacy/issues/944

**Comment by ryzyk-krzysiek** [comment]
I quickly checked because it's something I looked into in the past but never tried `ETMain` only `ETPro`.

It looks like the regression was introduced in `ETPro` which was merged into `Legacy` here https://github.com/etlegacy/etlegacy/commit/8dcc6eb4ea03c4afba94ce03098adcb6f6e76a96 and the difference in climb animations is change from 40fps to 20fps. (I was unaware of this commit untill now and it could be wise to check what else could have changed since there could be more broken stuff) 

ETMain
```
climb_up		2981	21	21	40	-1	0	0
climb_dis		3003	31	0	40	0	0	0
climb_start		3035	46	0	40	0	0	0
climb_down		3082	28	28	40	-1	0	0
```

Legacy and ETPro
```
climb_up		2981	21	21	20	-1	0	0
climb_dis		3003	31	0	20	0	0	0
climb_start		3035	46	0	20	0	0	0
climb_down		3082	28	28	20	-1	0	0
```

**Comment by Vorschreibung** [comment]
I've diffed them and looked through them, LGTM - grenade firing is the only one which had it's fps changed (this time doubled instead of halfed), but looks fine to me ingame, there's a lot of quirks in the released OG animations.

**Pull request merged**
