### PR TITLE
cgame: Improve noAmmoSound on failed weap switch

### PR DESCRIPTION
**Pull request by Vorschreibung**
Covers some previously missing cases (grenades, syringe) and adds a CVAR to disable it.

### CODE REVIEW

**Comment by Aranud** [comment]
I think it conflict with this https://github.com/etlegacy/etlegacy/blob/c29a150d0f5e1d4ecd09660dcbfffc9b34816617/src/cgame/cg_event.c#L2286-L2289.

No Ammo sound are played on event so enemy player can also hear it.

If you do the check only for the player it self, a sound will be missing.

**Comment by Vorschreibung** [comment]
> I think it conflict with this
> 
> https://github.com/etlegacy/etlegacy/blob/c29a150d0f5e1d4ecd09660dcbfffc9b34816617/src/cgame/cg_event.c#L2286-L2289
> 
> .
> No Ammo sound are played on event so enemy player can also hear it.
> 
> If you do the check only for the player it self, a sound will be missing.

Good catch!

**Comment by Vorschreibung** [comment]
@Aranud Now doesn't mess with the `noAmmoSound` of individual weapons and removes playing it in some cases where it would unnecessarily play it in the previous commit of this PR.

e.g. the moment you fire your last grenade, it played in the previous commit of this PR right before switching off to another weapon - it now switches off to another weapon without playing the sound and will only play once your try to switch to your empty grenades yourself

Ready for re-review

**Comment by Vorschreibung** [comment]
Resolved conflict, ready for review again.

**Pull request merged**
