### PR TITLE
client: added cl_slashCommand cvar so the user can choose whether a

### PR DESCRIPTION
**Pull request by JumptoHistory**
slash is required before cmds in the console
Couldn't this improve user experience? Let me know if it could cause trouble or I need to fix something.

### CODE REVIEW

**Comment by ensiform** [comment]
Why changing the ] to \ for input prompt?

Also might be better to have the cvar init in common.c and defined in qcommon.h so as to avoid it being NULL ever.

**Comment by JumptoHistory** [comment]
Well, I thought changing the prompt would make it easier to tell which mode you're on.
I'll look into it about the cvar init and definition.

**Comment by rmarquis** [comment]
This looks like an over-engineered solution to a problem that doesn't really exist.
I never ever type the slash because autocompletion does it.

**Comment by JumptoHistory** [comment]
Okay, I used to forget adding a slash before I implemented this in my custom build though.

**Comment by ensiform** [comment]
If you don't put slash, it turns command into chat, does it not?

**Comment by JumptoHistory** [comment]
Yeah, it's a bit embarrassing; not that I've given my referee password out in the global chat or anything but still.

**Comment by rmarquis** [comment]
Closing, because not needed. Just need to make use of completion, which is faster to use anyway.

**Pull request closed without merging**
