### PR TITLE
cgame: move popup shadow from althud flags to a seperate cvar

### PR DESCRIPTION
**Pull request by Aciz**
I don't think many people realize that drawing shadow on popups is even a possibility, I didn't know about this either until like a month ago, especially since it's not even included in the options menu for althud flags. So therefore, removed `cg_althudFlags 8` in favor of `cg_popupShadow`, I don't really understand why it was hidden there in the first place.

### CODE REVIEW

**Comment by BystryPL** [comment]
neat

**Comment by jackeri** [comment]
I would prefer moving away from the whole cg_althudflags thing (I originally added it way back when just to try to entice etpro players) but those flags / customizations / etc should be on the specific hud components. Not on global level imho.

**Comment by Aciz** [comment]
Yes, the whole HUD system should be rewrote ideally and get rid of as many HUD related cvars, and do everything through custom HUDs with generic parameters (x/y/w/h/alpha/shadow etc) and leave element-specific customization to cvars. But this requires a user-friendly way to edit HUDs, which is not what the current system with custom HUDs is.

**Comment by jackeri** [comment]
Which is why there needs to be an effort to add a basic hud editor (like in other mods / games).

**Pull request merged**
